name: CD Workflow

on:
  workflow_run:
    workflows: ["CI workflow"]
    types:
      - completed
  workflow_dispatch:
jobs:
    deploy:

        runs-on: self-hosted
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        #- name: Download  
        #  uses: actions/download-artifact@v4
        #  with:
        #    name: my-other-artifact
        #    github-token: ${{ secrets.GITHUB_TOKEN }} # token with actions:read permissions on target repo
        #    repository: actions/toolkit
        #    run-id: ${{ github.event.workflow_run.id }}

        - name: Load Docker Image
          run: docker load --input /tmp/nodeapp-v1.tar


        - name: Run Docker
          run: docker run --name=nodeapcontainer -dp 127.0.0.1:3000:3000 ${{ secrets.docker_hub_username }}/nodeapp-v1
          
        - name: Found ip Address
          run: echo "APP_IP=$(docker inspect --format='{{.NetworkSettings.IPAddress}}' nodeapcontainer)" >> $GITHUB_ENV

        - name: Print Latest Releases
          run: curl http://$APP_IP:3000/api/latest-releases 

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
              username: ${{ secrets.docker_hub_username }}
              password: ${{ secrets.docker_hub_access_token }}

        - name: Tag the image
          run: docker tag nodeapp-v1:latest ${{ secrets.docker_hub_username }}/nodeapp-v1:latest
      
        - name: Push the image to DockerHub
          run: docker push ${{ secrets.docker_hub_username }}/nodeapp-v1:latest