name: CD Workflow

on:
  workflow_run:
    workflows: ["CI workflow"]
    types:
      - completed
jobs:
    deploy:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Download artifact
          uses: actions/download-artifact@v3
          with:
            name: nodeapp-v1
