name: CD Workflow

on:
  #workflow_run:
   # workflows: ["CI workflow"]
   # types:
   #   - completed
   push:
   workflow_dispatch:
jobs:
    compile:
        name: Compile Prod
        # needs: test-deployment # This job depends on the successful completion of the int-deployment job

        uses: ./.github/workflows/reausable_workflow.yml
        with:
            environment_name: 'prod'
        secrets:    
            docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
            docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            sonar_token: ${{ secrets.SONAR_TOKEN }}
            sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
    deploy:
        needs: compile # This job depends on the successful completion of the int-deployment job

        runs-on: self-hosted
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Download artifact
          uses: actions/download-artifact@v3
          with:
            name: nodeappImage
            path: /tmp

        - name: Load Docker Image
          run: docker load < /tmp/nodeappImage.tar
        - name: Run Docker
          run: docker run -d --name nodeAppContainer -p 3000:3000 nodeappImage  &
        
        - name: Print Latest Releases
          run: curl http://localhost:3000/api/latest-releases 
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
              username: ${{ secrets.docker_hub_username }}
              password: ${{ secrets.docker_hub_access_token }}

        - name: Tag the image
          run: docker tag nodeapp-v1:latest ${{ secrets.docker_hub_username }}/nodeapp-v1:latest
      
        - name: Push the image to DockerHub
          run: docker push ${{ secrets.docker_hub_username }}/nodeapp-v1:latest