name: CD Workflow

on:
  workflow_run:
    workflows: ["CI workflow"]
    types:
      - completed
    branches:
      - main
jobs:
  
    deploy:
      
        if: ${{ github.event.workflow_run.conclusion == 'success' }}

        runs-on: self-hosted
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Download  
          uses: actions/download-artifact@v4
          with:
            name: nodeappImage
            github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
            repository: bmw-cd/CTW03463
            run-id: ${{ github.event.workflow_run.id }}

        - name: Load Docker Image
          run: |
              ls -la 
              docker load --input nodeapp-v1.tar


        - name: Run Docker
          run: docker run --name nodeapcontainer -dp 127.0.0.1:3000:3000 ${{ secrets.docker_hub_username }}/nodeapp-v1
          
        - name: echo "Waiting for application to start..."
          run: sleep 10 

    

        - name: Print Latest Releases
          run: |
                APP_IP=$(docker inspect --format='{{ range .NetworkSettings.Networks }}{{ .IPAddress }}{{ end }}' nodeapcontainer)
                echo "$APP_IP"
                echo "Attempting to connect to http://$APP_IP:3000/api/latest-releases"
                curl http://$APP_IP:3000/api/latest-releases

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
              username: ${{ secrets.docker_hub_username }}
              password: ${{ secrets.docker_hub_access_token }}

        - name: Set up Docker Buildx
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nodeapp-v1:latest

        - name: Shut Down Docker
          run: |
                docker stop nodeapcontainer
                docker rm nodeapcontainer
        