name: CI

on:
  push:
  workflow_dispatch:

jobs:
  dev-deployment:
    name: Deploy to Dev
    environment: dev
    runs-on: self-hosted
    outputs:
        image_output: ${{ steps.image_output.outputs.value }}
    steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: Test application
          run: npm test

        - name: SonarQube Scan
          uses: sonarsource/sonarqube-scan-action@master
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
            
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        - name: Set up Docker Buildx
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/v1
            outputs: type=docker,dest=/tmp/v1.tar
        
        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: myimage
            path: /tmp/v1.tar
        - name: Output the image name
          id: image_output
          run: |
            echo "The image name is ${{ secrets.DOCKER_HUB_USERNAME }}/v1"
            echo "::set-output name=foo::$BAR"
            echo "$BAR"  # add this line